---
- name: Install etcd packages
  yum: 
    name: 'etcd'
    state: present

- name: Edit the /etc/etcd/etcd.conf file
  template:
    src: 'etcd.conf.j2'
    dest: '/etc/etcd/etcd.conf'

- name: Start the etcd service and configure it to start when the system boots
  service:
    name: etcd.service
    state: started
    enabled: yes


