--- 
- name: Install the packages
  yum: 
    name: openstack-nova-compute

- name: Edit the /etc/nova/nova.conf file and complete the following actions
  template: 
    src: nova.conf_compute.j2
    dest: /etc/nova/nova.conf

- name: Start the Compute service including its dependencies and configure them to start automatically when the system boots
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
    loop:
      - 'libvirtd.service'
      - 'openstack-nova-compute.service'